### ISSUE TITLE
Not getting anything graphical at all

### ISSUE THREAD

**Issue by zoe-vb** [ChefKissInc/qemu-t8030#1]
I'm aware that there is no springboard support as of yet but I don't see the restore progress bar onscreen. And on the original project you were supposed to be able to see the bar.

**Comment by ChefKissInc** [comment]
> I'm aware that there is no springboard support as of yet but I don't see the restore progress bar onscreen. And on the original project you were supposed to be able to see the bar.

Hi @zoe-vb! Inside the Hack Different Discord server's dedicated channel, original author's Twitter and the SpringBoard issue located inside the now-archived repo, you can see the display working in various places, and eventually SprintBoard itself. However, the original author never published such display logic at all; the demonstration was merely a tease and he eventually decided to not publish it at all. No further details were provided.

**Comment by chris-pcguy** [comment]
"at all" doesn't seem correct by the time the pull request gets pushed.
Did I mentioned how much I hate software development, git, git-rebasing, signing git commits, and stuff?
Can this be closed?

**Comment by ChefKissInc** [comment]
Will be fixed by #3 I guess?

**Comment by chris-pcguy** [comment]
I guess not. We will have to see and fix for ourselves.

**Comment by ChefKissInc** [comment]
iOS 15 is more likely to work than 16, I think I read on Hack Different that a bunch of formats changed and some new patches are needed or something
