### ISSUE TITLE
Restore wont complete

### ISSUE THREAD

**Issue by zoe-vb** [ChefKissInc/qemu-t8030#4]
Looking in the serial output from qemu, the error says failed to restore apfs image and looking in idevicerestore it ends with failed to send filesystem payload near the end and then errors out after (timeout no data to read), just wondering why this was?

**Comment by ChefKissInc** [comment]
(It used to work like 4 months ago)

**Comment by zoe-vb** [comment]
yes but I wonder what could have changed, I used the original fork and patched the plist_from_memory function to still compile so I'm not sure where the error lies.

**Comment by ChefKissInc** [comment]
Can you fetch the exact error the restore process gives, cause I can't do the restore process. Got no companion VM and I don't really wanna make one

**Comment by zoe-vb** [comment]
ASR: __decompressChunk() error: 1000XSTA
ASR: fail
ASR: Could not restore - Input/output error
ASR STATUS: fail
restore_apfs_image : failed to restore an APFS image, error = 14

**Comment by ChefKissInc** [comment]
Is that on the iOS side?

**Comment by zoe-vb** [comment]
yes thats the ios serial log

**Comment by ChefKissInc** [comment]
I can find it online, but I don't see any solutions so far. It might be a communication error, not sure

**Comment by zoe-vb** [comment]
> I can find it online, but I don't see any solutions so far. It might be a communication error, not sure

sorry mb that was the idevicerestore error

**Comment by zoe-vb** [comment]
I think its a usbmuxd error to do with timeout https://github.com/libimobiledevice/libusbmuxd/blob/c7d7d1a03f65a27be2eddb13d1f2b0c0e7a60ec6/common/socket.c#L855

**Comment by ChefKissInc** [comment]
Can you try with the original fork to make sure I didn't break something with those changes to the frequencies

**Comment by zoe-vb** [comment]
the fork of qemu?

**Comment by chris-pcguy** [comment]
https://gist.github.com/chris-pcguy/b458716b7d4fd39c613f7196fb89ad92

Works for me.

**Comment by ChefKissInc** [comment]
@zoe-vb try that ^

**Comment by zoe-vb** [comment]
rather confused as to how to apply the git patch as git patch says error: patch failed: configure.ac:37
error: configure.ac: patch does not apply
error: patch failed: src/idevicerestore.c:1027
error: src/idevicerestore.c: patch does not apply
error: patch failed: src/ipsw.c:150
error: src/ipsw.c: patch does not apply
error: patch failed: src/restore.c:297
error: src/restore.c: patch does not apply

**Comment by chris-pcguy** [comment]
Of course it doesn't apply, on my VM it's not even using the latest trunk/commit. Look at the patch and change the files accordingly.

**Comment by zoe-vb** [comment]
yeah all done now, it's booted properly thanks
