### ISSUE TITLE
cool fork! but what works?

### ISSUE THREAD

**Issue by ThijsGaming** [ChefKissInc/qemu-t8030#5]
is the springboard working?

**Comment by ChefKissInc** [comment]
@ThijsGaming SpringBoard’s not working. But recovery mode has the apple logo and progress bar

**Comment by ThijsGaming** [comment]
ok does it have linux support?

**Comment by ChefKissInc** [comment]
I think you need macOS for some parts of the process, like editing the disk to add things to it. I don't use anything other than macOS personally; I have a MacBook Air. So I wouldn't know. Seems to run on `@chris-pcguy`'s machine though (which runs some Linux distro)
