### ISSUE TITLE
How do I use this fork of qemu

### ISSUE THREAD

**Issue by Rix565** [ChefKissInc/qemu-t8030#6]
I have linux if that helps

if it only supports mac os, please give instructions anyway because I may get it to work on Linux

**Comment by ChefKissInc** [comment]
@Rix565 the same way as the original repo

**Comment by Rix565** [comment]
wow you're fast xd

is this fork closer to launching Springboard than the OG repo?

**Comment by ChefKissInc** [comment]
@Rix565 Recovery apple logo and progress bar works

**Comment by Rix565** [comment]
cool! last question (i wont bother you after haha): is still being worked on?

**Comment by ChefKissInc** [comment]
@Rix565 There’s a lot of work involved in emulating an entire phone. Plus, I’ve got all my other projects too. The biggest obstacle right now is things like SEP. We’ll get them running eventually though

**Comment by Rix565** [comment]
ok! thanks for responding to my questions, i'll try to run the project later when i'll get some time free ^^
