### ISSUE TITLE
How to run the command to launch and/or restore?

### ISSUE THREAD

**Issue by FloofyProtoBomb** [ChefKissInc/qemu-t8030#7]
When I run it I get the following:
`qemu-system-aarch64: Please set firmware to SecureROM's path`

**Comment by ChefKissInc** [comment]
I suspect you ran the s8000 machine, which is only a stub for running SecureROM. This fork currently only supports running iOS using the t8030 machine. If this is not the case, then you are on our dev branch and you need to use master instead. For more information on how to run the machine, see the Wiki of the original repo
